FROM node:20

WORKDIR /app

COPY ./server/package*.json .
RUN npm install

COPY ./server .
COPY ./common ../common


# Transpile the TypeScript files
RUN npm run build

# Expose port 3000
EXPOSE 3000

CMD ["node", "/app/out/app/app/index.js"]
